config {
  type: "incremental", 
  schema: "dataset_silver_test",
  name: "ctabancos_silver",
}

INSERT INTO `hvr-dwh-dev-437001.dataset_silver_test.ctabancos_silver` (
  Cod,
  Des,
  cuenta_contable,
  usuario,
  fechora,
  Rut_Empresa
)
SELECT
  Cod,
  Des,
  cuenta_contable,
  usuario,
  SAFE_CAST(fechora AS DATETIME) AS fechora,
  Rut_Empresa
FROM
  `hvr-dwh-dev-437001.dataset_bronze.ctabancos`
